# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.



[[main]]
  name = "my thoughts"
  url = "#posts"
  weight = 20

[[main]]
  name = "projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "talks"
  url = "#events"
  weight = 40

[[main]]
  name = "publications"
  url = "#featured"
  weight = 50

[[main]]
  name = "courses"
  url = "courses/"
  weight = 60
  
[[main]]
  name = "patient education"
  url = "patient/"
  weight = 80
  

[[main]]
  name = "comment"
  url = "#contact"
  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
